print("Hello future microbiologist")
print("love my field")
print("Wanna create something beneficial for people.")
print("Love being productive.💖✨")
print("Learning python programming to enhance my research skills and data analysis capabilities.🧬🔬")