print("Hello World")
print("Myself Muqadas Fatima.")
print("I'm a future microbiologist.")
print("I love to explore the world of microorganisms and their impact on our lives.")
print("In my free time, I enjoy reading scientific articles and conducting experiments.")
print("I believe that understanding microorganisms can lead to advancements in medicine and environmental sustainability.")
print("I'm currently learning python programming to enhance my research skills and data analysis capabilities.")
print("This is my first python program, and I'm excited to continue learning and improving my programming skills.")
print("Every expert was once a beginner, and I'm committed to putting effort into becoming proficient in both microbiology and programming.")
print("Thank you for taking the time to read about me. I look forward to connecting with fellow enthusiasts in the field of microbiology and programming.")