print("Hello World")
print("Myself Muqadas Fatima.")
print("I'm a future microbiologist.")
print("I love to explore the world of microorganisms and their impact on our lives.")
print("In my free time, I enjoy reading scientific articles and conducting experiments.")
print("I believe that understanding microorganisms can lead to advancements in medicine and environmental sustainability.")